language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4
  - 8.0

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 8.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

    # Test LTS versions. This makes sure we do not use Symfony packages with version greater
    # than 3. Read more at https://github.com/symfony/lts
    - php: 7.3
      env:
        - DEPENDENCIES="symfony/lts:^3"
        - STATIC_ANALYSIS=true

before_install:
  - phpenv config-rm xdebug.ini || true
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit
  - |
    if [[ $STATIC_ANALYSIS == true ]]; then
      vendor/bin/phpcs .
      vendor/bin/phpstan analyze --level max .
    fi
