language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"

      # Test LTS versions. This makes sure we do not use Symfony packages with version greater
      # than 3. Read more at https://github.com/symfony/lts
    - php: 7.2
      env: DEPENDENCIES="symfony/lts:^3"

before_install:
  - phpenv config-rm xdebug.ini || true
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit
