name: PHP - Code quality

on:
  pull_request:

env:
  PHP_VERSION: 8.1

jobs:
  cache_dependencies:
    name: Fetch composer dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Fetch lastest changes
      uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # renovate: tag=v3.0.0
    - name: Prepare/restore dependencies cache
      uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # renovate: tag=v2.1.7
      with:
        # NOTE: the allows to reuse it if the composer.json has not changed
        key: composer/${{ runner.os }}/${{ hashFiles('**/composer.json') }}
        path: |
          composer.lock
          vendor/
    - name: Install/update dependencies
      uses: php-actions/composer@d936bcb900310224b9089aff3337f2221a8df9a0 # renovate: tag=v6.0.0
      with:
        php_version: ${{ env.PHP_VERSION }}
